FROM cypress/browsers:node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1
WORKDIR /usr/src/app
COPY ./package.json ./package-lock.json* ./
COPY ./cypress.config.js .
COPY ./cypress ./cypress
RUN npm ci
ENTRYPOINT [ "npx", "cypress", "run"]